version: '3.2'

services:
    consul:
        image: consul:1.0.1
        command: agent -dev -data-dir=/tmp -advertise=127.0.0.1 -bind=0.0.0.0 -client=0.0.0.0
        ports:
            - "8500:8500"

    mysql3306:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: upyun
            MYSQL_USER: runner
            MYSQL_PASSWORD: runner123456
        ports:
            - "3306:3306"

    mysql3307:
        image: mysql:5.7
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: upyun
            MYSQL_USER: runner
            MYSQL_PASSWORD: runner123456
        ports:
            - "3307:3306"

    slardar:
        links:
            - consul
            - mysql3307
            - mysql3306
        image: huangnauh/slardar:test
        volumes:
            - type: bind
              source: ./nginx/conf
              target: /usr/local/slardar/nginx/conf
        ports: 
            - "1895:1895"
            - "1995:1995"
            - "3151:3151"
            - "3251:3251"
            - "3351:3351"
            - "3141:3141"
            - "3131:3131"
            - "8080:8080"


